package middleware

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"regexp"
	"strings"
	"sync"
	"sync/atomic"
	"unicode/utf8"

	"github.com/finemcp/finemcp"
)

// maxRefDepth is the maximum number of $ref resolutions allowed in a single
// validation path. Prevents infinite loops from circular $ref definitions.
const maxRefDepth = 32

// Validation returns a middleware that validates tool input against the tool's
// JSON Schema (set via WithInputSchema or auto-generated by NewTypedTool).
//
// Behaviour:
//   - No schema on context → pass through (no validation).
//   - SkipValidation flag set → pass through.
//   - Input does not conform to schema → returns a tool error (isError: true)
//     with a human-readable message listing the violated constraints.
//
// Supported JSON Schema keywords (Draft 2020-12 subset):
//   - type, required, properties — object structure
//   - enum — restrict values to a fixed set
//   - pattern — regex validation for strings
//   - minimum, maximum, exclusiveMinimum, exclusiveMaximum — numeric range
//   - minLength, maxLength — string length constraints
//   - minItems, maxItems, uniqueItems — array constraints
//   - items — array element schema
//   - additionalProperties — object strictness (false or schema)
//   - $ref, $defs — internal schema references
//
// Integer fields accept whole-number floats (e.g. 42.0).
//
// Usage:
//
//	server.Use(middleware.Validation())
func Validation() finemcp.Middleware {
	return func(next finemcp.ToolHandler) finemcp.ToolHandler {
		return func(ctx context.Context, input []byte) ([]byte, error) {
			// Skip if opted out.
			if finemcp.SkipValidationFromCtx(ctx) {
				return next(ctx, input)
			}

			schemaRaw := finemcp.ToolSchemaFromCtx(ctx)
			if schemaRaw == nil {
				return next(ctx, input)
			}

			schema, ok := normalizeSchema(schemaRaw)
			if !ok {
				// Schema is not something we can validate against; pass through.
				return next(ctx, input)
			}

			// Extract $defs for $ref resolution within this schema.
			defs := extractDefs(schema)

			// Parse the input JSON into a generic map.
			var data map[string]any
			if len(input) > 0 {
				if err := json.Unmarshal(input, &data); err != nil {
					return nil, fmt.Errorf("invalid JSON input: %w", err)
				}
			}

			// Validate against the schema.
			if errs := validateObject(schema, data, "", defs, maxRefDepth); len(errs) > 0 {
				return nil, fmt.Errorf("validation failed: %s", strings.Join(errs, "; "))
			}

			return next(ctx, input)
		}
	}
}

// normalizeSchema converts the schema value (map[string]any, json.RawMessage, etc.)
// into a map[string]any. Returns false if conversion is not possible.
func normalizeSchema(v any) (map[string]any, bool) {
	switch s := v.(type) {
	case map[string]any:
		return s, true
	case json.RawMessage:
		var m map[string]any
		if err := json.Unmarshal(s, &m); err != nil {
			return nil, false
		}
		return m, true
	case []byte:
		var m map[string]any
		if err := json.Unmarshal(s, &m); err != nil {
			return nil, false
		}
		return m, true
	default:
		// Try JSON round-trip as a fallback.
		b, err := json.Marshal(v)
		if err != nil {
			return nil, false
		}
		var m map[string]any
		if err := json.Unmarshal(b, &m); err != nil {
			return nil, false
		}
		return m, true
	}
}

// ── $ref / $defs ────────────────────────────────────────────────────

// extractDefs returns the $defs map from a root schema, or nil if absent.
func extractDefs(schema map[string]any) map[string]any {
	if defs, ok := schema["$defs"].(map[string]any); ok {
		return defs
	}
	return nil
}

// resolveRef resolves a JSON Pointer $ref of the form "#/$defs/<name>".
// Returns the resolved schema or nil if the reference is invalid/unresolvable.
// Only internal references (starting with "#/$defs/") are supported.
func resolveRef(ref string, defs map[string]any) map[string]any {
	const prefix = "#/$defs/"
	if !strings.HasPrefix(ref, prefix) {
		return nil
	}
	name := ref[len(prefix):]
	if name == "" || defs == nil {
		return nil
	}
	if resolved, ok := defs[name].(map[string]any); ok {
		return resolved
	}
	return nil
}

// resolveSchema follows a $ref chain (A→B→C) until a concrete schema is
// reached or depth is exhausted. Each hop consumes one unit of depth budget
// to guard against circular $ref definitions.
func resolveSchema(schema map[string]any, defs map[string]any, depth int) map[string]any {
	for depth > 0 {
		ref, ok := schema["$ref"].(string)
		if !ok || ref == "" {
			return schema
		}
		resolved := resolveRef(ref, defs)
		if resolved == nil {
			return schema // unresolvable — validate against original
		}
		schema = resolved
		depth--
	}
	return schema // depth exhausted — stop resolving
}

// ── Object validation ───────────────────────────────────────────────

// validateObject checks the data against an object schema.
// prefix is the current field path (empty at root).
// depth tracks the remaining $ref resolution budget; it is only consumed
// inside resolveSchema when an actual $ref hop occurs, not by structural
// nesting, so deeply nested schemas without $ref never exhaust the budget.
func validateObject(schema map[string]any, data map[string]any, prefix string, defs map[string]any, depth int) []string {
	schema = resolveSchema(schema, defs, depth)
	var errs []string

	// Check required fields.
	if req, ok := schema["required"]; ok {
		required := toStringSlice(req)
		for _, field := range required {
			if data == nil {
				errs = append(errs, fmt.Sprintf("missing required field: %s", qualifyField(prefix, field)))
				continue
			}
			if _, exists := data[field]; !exists {
				errs = append(errs, fmt.Sprintf("missing required field: %s", qualifyField(prefix, field)))
			}
		}
	}

	// Check property types.
	props, _ := schema["properties"].(map[string]any)
	if props == nil || data == nil {
		return errs
	}

	// Resolve additionalProperties once before the loop.
	ap, hasAP := schema["additionalProperties"]
	var apSchema map[string]any // non-nil when extra props must be validated against a schema
	apDeny := false             // true when extra props are forbidden entirely
	if hasAP {
		switch v := ap.(type) {
		case bool:
			apDeny = !v
		case map[string]any:
			apSchema = resolveSchema(v, defs, depth)
		}
	}

	// Single pass over data: validate known properties and enforce
	// additionalProperties in one iteration.
	for field, val := range data {
		fieldPath := qualifyField(prefix, field)

		propSchemaRaw, inProps := props[field]
		if !inProps {
			// Unknown field — handle additionalProperties.
			if apDeny {
				errs = append(errs, fmt.Sprintf("%s: additional property not allowed", fieldPath))
			} else if apSchema != nil {
				errs = append(errs, validateValue(apSchema, val, fieldPath, defs, depth)...)
			}
			continue
		}

		ps, ok := propSchemaRaw.(map[string]any)
		if !ok {
			continue
		}
		ps = resolveSchema(ps, defs, depth)
		errs = append(errs, validateValue(ps, val, fieldPath, defs, depth)...)
	}

	return errs
}

// ── Value validation ────────────────────────────────────────────────

// validateValue checks a single value against its property schema.
// depth is the $ref resolution budget and is passed through unchanged;
// resolveSchema consumes it only when an actual $ref hop occurs.
func validateValue(propSchema map[string]any, val any, path string, defs map[string]any, depth int) []string {
	propSchema = resolveSchema(propSchema, defs, depth)
	var errs []string

	// enum — applicable to any type.
	if enumErrs := validateEnum(propSchema, val, path); len(enumErrs) > 0 {
		return enumErrs // enum mismatch is conclusive
	}

	expectedType, _ := propSchema["type"].(string)
	if expectedType == "" {
		return nil // no type constraint
	}

	switch expectedType {
	case "string":
		s, ok := val.(string)
		if !ok {
			return []string{fmt.Sprintf("%s: expected string, got %s", path, jsonTypeName(val))}
		}
		errs = append(errs, validateStringConstraints(propSchema, s, path)...)

	case "integer":
		n, ok := toFloat64(val)
		if !ok {
			return []string{fmt.Sprintf("%s: expected integer, got %s", path, jsonTypeName(val))}
		}
		if n != math.Trunc(n) {
			return []string{fmt.Sprintf("%s: expected integer, got non-whole number", path)}
		}
		errs = append(errs, validateNumericConstraints(propSchema, n, path)...)

	case "number":
		n, ok := toFloat64(val)
		if !ok {
			return []string{fmt.Sprintf("%s: expected number, got %s", path, jsonTypeName(val))}
		}
		errs = append(errs, validateNumericConstraints(propSchema, n, path)...)

	case "boolean":
		if _, ok := val.(bool); !ok {
			return []string{fmt.Sprintf("%s: expected boolean, got %s", path, jsonTypeName(val))}
		}

	case "object":
		obj, ok := val.(map[string]any)
		if !ok {
			return []string{fmt.Sprintf("%s: expected object, got %s", path, jsonTypeName(val))}
		}
		return validateObject(propSchema, obj, path, defs, depth)

	case "array":
		arr, ok := val.([]any)
		if !ok {
			return []string{fmt.Sprintf("%s: expected array, got %s", path, jsonTypeName(val))}
		}
		return validateArray(propSchema, arr, path, defs, depth)
	}

	return errs
}

// toFloat64 converts numeric JSON values (float64, json.Number) to float64.
func toFloat64(val any) (float64, bool) {
	switch n := val.(type) {
	case float64:
		return n, true
	case json.Number:
		f, err := n.Float64()
		return f, err == nil
	default:
		return 0, false
	}
}

// ── Enum ────────────────────────────────────────────────────────────

// validateEnum checks that val is one of the allowed enum values.
func validateEnum(schema map[string]any, val any, path string) []string {
	enumRaw, ok := schema["enum"]
	if !ok {
		return nil
	}
	allowed, ok := enumRaw.([]any)
	if !ok {
		return nil // malformed enum — skip
	}
	for _, a := range allowed {
		if jsonEqual(a, val) {
			return nil
		}
	}

	// Build a readable list of allowed values.
	labels := make([]string, len(allowed))
	for i, a := range allowed {
		b, _ := json.Marshal(a)
		labels[i] = string(b)
	}
	return []string{fmt.Sprintf("%s: value must be one of [%s]", path, strings.Join(labels, ", "))}
}

// jsonEqual compares two JSON-decoded values for equality.
// Handles float64 ↔ float64 and string ↔ string; for complex types
// falls back to fmt.Sprintf comparison.
func jsonEqual(a, b any) bool {
	switch av := a.(type) {
	case float64:
		if bv, ok := b.(float64); ok {
			return av == bv
		}
	case string:
		if bv, ok := b.(string); ok {
			return av == bv
		}
	case bool:
		if bv, ok := b.(bool); ok {
			return av == bv
		}
	case nil:
		return b == nil
	}
	return fmt.Sprintf("%v", a) == fmt.Sprintf("%v", b)
}

// ── String constraints ──────────────────────────────────────────────

// regexpCache caches compiled regular expressions for the pattern keyword.
// Bounded to regexpCacheMax entries; when the limit is reached the entire
// cache is flushed. This prevents unbounded memory growth if schemas contain
// many distinct patterns (e.g. from untrusted input).
const regexpCacheMax = 256

var (
	regexpCache    sync.Map     // map[string]*regexp.Regexp
	regexpCacheLen atomic.Int64 // approximate entry count
)

// getRegexp returns a compiled regexp for the given pattern, using a cache.
func getRegexp(pattern string) (*regexp.Regexp, error) {
	if v, ok := regexpCache.Load(pattern); ok {
		return v.(*regexp.Regexp), nil
	}
	re, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	// Evict all entries when the cache is full. This is coarse-grained but
	// simple and perfectly adequate — schemas are nearly always static so the
	// cache quickly rebuilds and rarely (if ever) hits the cap in practice.
	if regexpCacheLen.Load() >= regexpCacheMax {
		regexpCache.Range(func(key, _ any) bool {
			regexpCache.Delete(key)
			return true
		})
		regexpCacheLen.Store(0)
	}
	regexpCache.Store(pattern, re)
	regexpCacheLen.Add(1)
	return re, nil
}

// validateStringConstraints checks minLength, maxLength, and pattern.
func validateStringConstraints(schema map[string]any, s string, path string) []string {
	var errs []string

	runeLen := utf8.RuneCountInString(s)

	if v, ok := toFloat64Value(schema["minLength"]); ok {
		min := int(v)
		if runeLen < min {
			errs = append(errs, fmt.Sprintf("%s: string length %d is less than minimum %d", path, runeLen, min))
		}
	}

	if v, ok := toFloat64Value(schema["maxLength"]); ok {
		max := int(v)
		if runeLen > max {
			errs = append(errs, fmt.Sprintf("%s: string length %d exceeds maximum %d", path, runeLen, max))
		}
	}

	if pattern, ok := schema["pattern"].(string); ok && pattern != "" {
		re, err := getRegexp(pattern)
		if err != nil {
			errs = append(errs, fmt.Sprintf("%s: invalid pattern %q: %v", path, pattern, err))
		} else if !re.MatchString(s) {
			errs = append(errs, fmt.Sprintf("%s: string does not match pattern %q", path, pattern))
		}
	}

	return errs
}

// ── Numeric constraints ─────────────────────────────────────────────

// validateNumericConstraints checks minimum, maximum, exclusiveMinimum,
// exclusiveMaximum.
func validateNumericConstraints(schema map[string]any, n float64, path string) []string {
	var errs []string

	if v, ok := toFloat64Value(schema["minimum"]); ok {
		if n < v {
			errs = append(errs, fmt.Sprintf("%s: value %v is less than minimum %v", path, n, v))
		}
	}
	if v, ok := toFloat64Value(schema["maximum"]); ok {
		if n > v {
			errs = append(errs, fmt.Sprintf("%s: value %v exceeds maximum %v", path, n, v))
		}
	}
	if v, ok := toFloat64Value(schema["exclusiveMinimum"]); ok {
		if n <= v {
			errs = append(errs, fmt.Sprintf("%s: value %v must be greater than %v", path, n, v))
		}
	}
	if v, ok := toFloat64Value(schema["exclusiveMaximum"]); ok {
		if n >= v {
			errs = append(errs, fmt.Sprintf("%s: value %v must be less than %v", path, n, v))
		}
	}

	return errs
}

// ── Array validation ────────────────────────────────────────────────

// validateArray checks each element against the items schema and enforces
// minItems, maxItems, and uniqueItems constraints.
func validateArray(schema map[string]any, arr []any, path string, defs map[string]any, depth int) []string {
	var errs []string

	// minItems / maxItems.
	arrLen := len(arr)

	if v, ok := toFloat64Value(schema["minItems"]); ok {
		min := int(v)
		if arrLen < min {
			errs = append(errs, fmt.Sprintf("%s: array length %d is less than minItems %d", path, arrLen, min))
		}
	}
	if v, ok := toFloat64Value(schema["maxItems"]); ok {
		max := int(v)
		if arrLen > max {
			errs = append(errs, fmt.Sprintf("%s: array length %d exceeds maxItems %d", path, arrLen, max))
		}
	}

	// uniqueItems.
	if ui, ok := schema["uniqueItems"]; ok {
		if unique, isBool := ui.(bool); isBool && unique {
			errs = append(errs, validateUniqueItems(arr, path)...)
		}
	}

	// Per-element validation via items schema.
	items, ok := schema["items"].(map[string]any)
	if !ok {
		return errs
	}
	items = resolveSchema(items, defs, depth)

	for i, elem := range arr {
		elemPath := fmt.Sprintf("%s[%d]", path, i)
		errs = append(errs, validateValue(items, elem, elemPath, defs, depth)...)
	}
	return errs
}

// validateUniqueItems checks that all array elements are distinct.
// Uses JSON-serialized form for cross-type comparison.
func validateUniqueItems(arr []any, path string) []string {
	seen := make(map[string]int, len(arr))
	var errs []string
	for i, elem := range arr {
		key := jsonKey(elem)
		if first, dup := seen[key]; dup {
			errs = append(errs, fmt.Sprintf("%s[%d]: duplicate of element at index %d", path, i, first))
			break // report first duplicate only
		}
		seen[key] = i
	}
	return errs
}

// jsonKey returns a canonical string representation of a JSON-decoded value
// suitable for deduplication.
func jsonKey(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprintf("%v", v)
	}
	return string(b)
}

// ── Helpers ─────────────────────────────────────────────────────────

// qualifyField returns the dot-separated field path.
func qualifyField(prefix, field string) string {
	if prefix == "" {
		return field
	}
	return prefix + "." + field
}

// toFloat64Value extracts a float64 from a schema value that may be float64
// or json.Number. Returns false if the value is nil or non-numeric.
func toFloat64Value(v any) (float64, bool) {
	if v == nil {
		return 0, false
	}
	switch n := v.(type) {
	case float64:
		return n, true
	case json.Number:
		f, err := n.Float64()
		return f, err == nil
	case int:
		return float64(n), true
	case int64:
		return float64(n), true
	default:
		return 0, false
	}
}

// toStringSlice converts an any value to []string.
// Handles []string, []any (with string elements).
func toStringSlice(v any) []string {
	switch s := v.(type) {
	case []string:
		return s
	case []any:
		out := make([]string, 0, len(s))
		for _, e := range s {
			if str, ok := e.(string); ok {
				out = append(out, str)
			}
		}
		return out
	}
	return nil
}

// jsonTypeName returns a human-readable name for a JSON value's Go type.
func jsonTypeName(v any) string {
	switch v.(type) {
	case nil:
		return "null"
	case bool:
		return "boolean"
	case float64, json.Number:
		return "number"
	case string:
		return "string"
	case map[string]any:
		return "object"
	case []any:
		return "array"
	default:
		return fmt.Sprintf("%T", v)
	}
}
